import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: '#A5C9CA',
  },
  body: {
    flex: 1,
    backgroundColor: '#A5C9CA',
    paddingTop: 50
  },
  inputContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 30,
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#FFF',
  },
  inputText: {
    flex: 1,
    fontSize: 18,
    paddingLeft: 5
  },
  itemsContainer: {
    flex: 1,
    backgroundColor: '#A5C9CA',
    paddingTop: 30,
  },
  itemsFlatList: {
    gap: 15,
  },
  itemContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 35,
    padding: 15,
    borderRadius: 10,
    backgroundColor: '#FFF',
    shadowColor: "#000",
    shadowOffset: {
    	width: 0,
    	height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  itemText: {
    flex: 1,
    fontSize: 18,
    fontWeight: "bold",
    paddingLeft: 3,
  },
  itemDone: {
    flex: 0.1,
    padding: 5,
    textAlign: "center",
    fontSize: 24,
    marginHorizontal: 3,
    color: "green",
  },
  itemClose: {
    flex: 0.1,
    padding: 5,
    textAlign: "center",
    fontSize: 24,
    marginHorizontal: 3,
    color: "red",
  },
  modalView: {
    flex: 1,
    paddingTop: 100,
    backgroundColor: '#A5C9CA',
  },
  modalContainer: {
    backgroundColor: "white",
    flex: 0.35,
    marginHorizontal: 30,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "space-around",
  },
  modalTextsContainer: {
    gap: 30,
  },
  modalDate: {
    fontSize: 18,
    textAlign: "center",
  },
  modalText: {
    marginHorizontal: 20,
    textAlign: "center",
    fontSize: 24,
    fontWeight: "bold",
  },
  modalButtonsContainer: {
    flexDirection: "row",
    gap: 30,
  },
  modalDeleteText: {
    width: 80,
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    textAlignVertical: "center",
    padding: 7,
    borderWidth: 2,
    borderRadius: 15,
    borderColor: "#B70404",
    color: "#B70404",
  },
  modalDoneText: {
    width: 80,
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    textAlignVertical: "center",
    padding: 7,
    borderWidth: 2,
    borderRadius: 15,
    borderColor: "#1B9C85",
    color: "#1B9C85",
  },
  modalCloseText: {
    width: 80,
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    textAlignVertical: "center",
    padding: 7,
    borderWidth: 2,
    borderRadius: 15,
    borderColor: "#000000",
    color: "#000000",
  },
});